name: self-check
on: push
jobs:
  code-quality:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: make install
      - name: lint
        run: make lint
      - name: test-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
          make test-coverage
          ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
